version: 0.0
os: linux   
hooks:
  BeforeInstall:
    - location: scripts/login_pull.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/stop_containers.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: ubuntu

